---
### Uses template to build the base configuration (mainly non-fabric) using mostly the variables from base.yml) ###

- name: "SYS >> Generating base config snippets"
  template:
    src: "{{ ansible_network_os }}/bse_tmpl.j2"
    dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/config/base.conf"
  changed_when: False           # Stops it reporting changes in playbook summary
  check_mode: False             # These tasks still make changes when in check mode
  # tags: [bse, bse_fbc, full]