---
### Uses template to build the tenant configuration, so VRFs, SVIs, VXLANs and VLANs using variables from services_tenant.yml) ###

- name: "Getting interface list"
  block:
  # - include_vars: "vars/services_interface.yml"         DONT need these can delete include_vars from all roles
  # - include_vars: "vars/fabric.yml"
  - name: "SYS >> Getting interface list"
    set_fact:
      flt_svc_intf: "{{ svc_intf.intf |create_svc_intf_dm(inventory_hostname, svc_intf.adv, fbc.adv.bse_intf) }}"
  - name: "SYS >> Generating service_tenant config snippets"
    template:
      src: "svc_intf_tmpl.j2"
      dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/config/svc_intf.conf"
    changed_when: False           # Stops it reporting changes in playbook summary
    check_mode: False             # These tasks still make changes when in check mode
    when: bse.device_name.spine not in inventory_hostname
