---
# This playbook is used to to deploy leaf and spine topology

- name: "Deploy Leaf and Spine DC"
  hosts: all
  # hosts: DC1-N9K-BORDER02
  # hosts: DC1-N9K-LEAF01:DC1-N9K-LEAF02
  # hosts: DC1-N9K-SPINE02
  connection: local
  vars_files:
    - vars/ansible.yml            # All variables start with ans.
    - vars/base.yml               # All variables start with bse.
    - vars/fabric.yml             # All variables start with fbc.
    - vars/services_tenant.yml    # All variables start with svc_tnt
    - vars/services_interface.yml    # All variables start with svc_tnt
    # Used to test pre_validation checls
    # - unit_test/base.yml
    # - unit_test/fabric.yml
    # - unit_test/services_tenant.yml
    # - unit_test/services_interface.yml

######################## 1. Validates the input data (in var_files) and creates the file strucuture ########################
  pre_tasks:
    # 1a. Validate that the required elements in the variable files are all defined and in the correct format
    - name: "Validate the contents of the variable files"
      block:
      - name: "SYS >> Validating the contents of base.yml"
        assert:
          # Uses a filter pluggin input_validate to do the validating and returns the outcome to the Anisble assert module
          that: "{{ bse.device_name | input_bse_validate(bse.addr, bse.users) }} == 'base.yml unittest pass'"
          fail_msg: "{{ bse.device_name | input_bse_validate(bse.addr, bse.users) }}"
      - name: "SYS >> Validating the contents of fabric.yml"
        assert:
          that: "{{ fbc.network_size | input_fbc_validate(fbc.num_intf, fbc.route, fbc.acast_gw_mac, fbc.adv.bse_intf, fbc.adv.lp,
                   fbc.adv.mlag, fbc.adv.addr_incre) }} == 'fabric.yml unittest pass'"
          fail_msg: "{{ fbc.network_size | input_fbc_validate(fbc.num_intf, fbc.route, fbc.acast_gw_mac, fbc.adv.bse_intf,
                      fbc.adv.lp, fbc.adv.mlag, fbc.adv.addr_incre) }}"
      - name: "SYS >> Validating the contents of services_tenant.yml"
        assert:
          that: "{{ svc_tnt.tnt | input_svc_tnt_validate(svc_tnt.adv) }} == 'services_tenant.yml unittest pass'"
          fail_msg: "{{ svc_tnt.tnt | input_svc_tnt_validate(svc_tnt.adv) }}"
      - name: "SYS >> Validating the contents of services_interfaces.yml"
        assert:
          that: "{{ svc_intf.intf | input_svc_intf_validate(svc_intf.adv, fbc.network_size, svc_tnt.tnt, bse.device_name,
                   fbc.num_intf) }} == 'services_interface.yml unittest pass'"
          fail_msg: "{{ svc_intf.intf | input_svc_intf_validate(svc_intf.adv, fbc.network_size, svc_tnt.tnt, bse.device_name, fbc.num_intf) }}"
      run_once: true        # Doesnt need to run for every hosts as just validating files.
      tags: [pre_val, full]

    # - name: "TO test a new variable file"
    #   block:
    #   - set_fact:
    #         test: "{{ svc_intf.intf | input_svc_intf_validate(svc_intf.adv, fbc.network_size, svc_tnt.tnt, bse.device_name, fbc.num_intf) }}"
    #   - debug:
    #       var=test
    #   run_once: true
    #   tags: [test]

    # 1b. Create the file structure
    - name: "Create the localhost environment"
      block:
      - name: "SYS >> Cleaning up the directory"
        file:
          path: "{{ ans.dir_path }}"
          state: absent
        run_once: true        # Only needs to run for one host as delets the root directory
        changed_when: False
      - name: "SYS >> Creating file structure"
        file: path="{{ ans.dir_path }}/{{ item }}" state=directory
        changed_when: False         # Stops it reporting changes in playbook summary
        # Config stores the config snippets, diff the chnages to configuration made and reports the compliance result of desired Vs expected state
        loop: [reports, diff, "{{ inventory_hostname }}/config", "{{ inventory_hostname }}/validate"]
      check_mode: False             # These tasks still make changes when in check mode
      tags: [dir, full]

######################## 2. Create the config snippets from templates ########################
  tasks:
    - name: Builds the base config snippet
      import_role:
        name: base
      tags: [bse, bse_fbc, bse_fbc_svc, full]
    - name: Builds the fabric config snippet
      import_role:
        name: fabric
      tags: [fbc, bse_fbc, bse_fbc_svc, full]
    - name: Builds the tenant config snippets
      import_role:
        name: services
        tasks_from: svc_tnt
      tags: [tnt, svc, bse_fbc_svc, full]
    - name: Builds the interface config snippets
      import_role:
        name: services
        tasks_from: svc_intf
      tags: [intf, svc, bse_fbc_svc, full]

    - name: Interface cleanup
      import_role:
        name: intf_cleanup
      tags: [cln, fbc, bse_fbc, intf, bse_fbc_svc, full]

######################## 3. Join the config snippets into one file and deploy ########################
  # tasks:
  # 3a. Join the all config snippets from the folder into the one big file
    - name: "SYS >> Joining config snippets into one file"
      assemble:
        src: "{{ ans.dir_path }}/{{ inventory_hostname }}/config"
        dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/config/config.cfg"
        regexp: '\.conf$'           # Ensures only joins the files created by the roles
      changed_when: False           # Stops it reporting changes in playbook summary
      check_mode: False             # These tasks still make changes when in check mode
      tags: [asmb, bse_fbc, bse_fbc_svc, full]

  # 3b. Replace the configuration on the devices with the config in the assembled config file
    - name: "NET >> Applying changes using replace config"
      napalm_install_config:
        provider: "{{ ans.creds_all }}"
        dev_os: "{{ ansible_network_os }}"
        # NXOS takes between 70 to 100 seconds to deploy all changes so defaul timesout needed increasing
        timeout: 180
        config_file: "{{ ans.dir_path }}/{{ inventory_hostname }}/config/config.cfg"
        commit_changes: True            # Set to true as use Ansible check_mode to do dry runs
        replace_config: True            # Replacing config rather than merging
        diff_file: "{{ ans.dir_path }}/diff/{{ inventory_hostname }}.txt"
        get_diffs: True                 # All diffs re save to file, can user with checkmode to see expected
      register: changes
      tags: [cfg, cfg_diff, full]
    - debug: var=changes.msg.splitlines()
      tags: [cfg_diff]

  # 3c. Rollback changes
    - name: "NET >> Rolling back configuration"
      block:
      - net_get:
          src: rollback_config.txt
          dest :  "{{ ans.dir_path }}/{{ inventory_hostname }}/config/rollback_config.txt"
        check_mode: False
        connection: network_cli
      - napalm_install_config:
          provider: "{{ ans.creds_all }}"
          dev_os: "{{ ansible_network_os }}"
          timeout: 120                    # Needed as with default 60 will timeout before full rollback complete
          config_file: "{{ ans.dir_path }}/{{ inventory_hostname }}/config/rollback_config.txt"
          commit_changes: True            # Set to true as use Ansible check_mode to do dry runs
          replace_config: True            # Replacing config rather than merging
          diff_file: "{{ ans.dir_path }}/diff/{{ inventory_hostname }}_rollback.txt"
          get_diffs: True
        register: changes
      tags: [rb, rb_diff]
    - debug: var=changes.msg.splitlines()
      tags: [rb_diff]

######################## 4. Produce reports on fabric actual Vs desired state ########################
# None of the validation tasks will run if it is in check-mode, although building the template file will be run

  post_tasks:
    - name: SYS >> Waiting 10 seconds for convergence before runnning post_tasks
      wait_for:
        timeout: 10
      run_once: true
      tags: [full]
    - name: Import napalm_validate tasks to compare actual vs desired state
      import_role:
        name: validate
        tasks_from: nap_val
      # tags: [nap_val, post_val, full]

    - name: Import custom_validate tasks to compare actual vs desired state
      block:
      - name: Import custom_validate tasks to compare actual vs desired state
        import_role:
          name: validate
          tasks_from: cus_val
      # tags are within the role
