- hosts: localhost
  gather_facts: no
  tasks:
  - name: "SYS >> Pass through Python Filter"
    set_fact:     # Passes output through filter with bgp_neigh variable
      bgp_table: "{{ bgp_output.ansible_facts | bgp_filter(inventory_hostname, bgp_neigh) }}"
    changed_when: False
  tags: [bgp]
  when: os == 'nxos'




