### Uses napalm_validate to verify that the actual state of LLDP, BGP and ping matches the desired state ###

---
# 4a. TEMPLATE: Creates validation file of expected desired state from the input data
- name: "Create naplam desired state Validation files"
  block:
  - name: "SYS >> Creating the Napalm validation files"
    template:
      src: napalm/val_tmpl.j2
      dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/validate/napalm_desired_state.yml"
    changed_when: False
  tags: val_tmpl

# 4b. NAPALM: Napalm_validate used to gather and compare actual and desired state on all device types
- name: "Create napalm compliance report"
  block:
  - name: "NET >> Validating Connections, BGP and Reachability"
    # Generates actual_state and compares against the desired state
    napalm_validate:
      provider: "{{ ans.creds_all }}"
      dev_os: "{{ ansible_network_os }}"
      # Have to use filter plugin as naplam_validate wont take ~/ so filter gets full path
      validation_file: "{{ ans.dir_path | fix_home_path() }}/{{ inventory_hostname }}/validate/napalm_desired_state.yml"
    register: nap_val
    ignore_errors: yes            # Needed so continues to the FAIL play

# 4c. REPORT: The compliance Report is saved to file no matter what the outcome. Output to screen is not verbose unless non-compliant.
  - name: "SYS >> Saving compliance reports to {{ ans.dir_path }}/reports/"
    copy: content="{{ nap_val.compliance_report }}" dest={{ ans.dir_path }}/reports/{{ inventory_hostname }}_compliance_report.json
    changed_when: False
    ignore_errors: yes          # Needed so continues to the FAIL play
  - name: "FAIL >> Compliance check failed"
    fail:
      msg: "Non-compliant state encountered. Refer to the full report in {{ ans.dir_path }}/reports/{{ inventory_hostname }}_compliance_report.json"
    when: not nap_val.compliance_report.complies
  when: not ansible_check_mode          # Dont want to run validation in check_mode