### Uses napalm_validate to verify that the actual state of LLDP, BGP and ping matches the desired state ###

---
# 4a. TEMPLATE: Creates validation file of expected desired state from the input data
- name: "SYS >> Creating bse_fbc napalm_validate validation file"
  template:
    src: napalm/bse_fbc_val_tmpl.j2
    dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/validate/napalm_desired_state.yml"
  changed_when: False
  tags: [nap_val_fbc_bse]

- name: "SYS >> Creating bse_fbc and svc_tnt napalm_validate validation file"
  template:
    src: napalm/svc_tnt_val_tmpl.j2
    dest: "{{ ans.dir_path }}/{{ inventory_hostname }}/validate/napalm_desired_state.yml"
  changed_when: False
  tags: [nap_val_tnt,nap_val_svc, nap_val, post_val, full]


# 4b. NAPALM: Napalm_validate used to gather and compare actual and desired state on all device types
- name: "Create napalm compliance report"
  block:
  - name: "NET >> Validating LLDP Connections, BGP and Reachability"
    # Generates actual_state and compares against the desired state
    napalm_validate:
      provider: "{{ ans.creds_all }}"
      dev_os: "{{ ansible_network_os }}"
      # Have to use filter plugin as naplam_validate wont take ~/ so filter gets full path
      validation_file: "{{ ans.dir_path | fix_home_path() }}/{{ inventory_hostname }}/validate/napalm_desired_state.yml"
    register: nap_val
    ignore_errors: yes            # Needed so continues to the FAIL play

# 4c. REPORT: The compliance Report is saved to file no matter what the outcome. Output to screen is not verbose unless non-compliant.
  - name: "SYS >> Saving compliance reports to {{ ans.dir_path }}/reports/"
    copy: content="{{ nap_val.compliance_report }}" dest={{ ans.dir_path }}/reports/{{ inventory_hostname }}_compliance_report.json
    changed_when: False
    ignore_errors: yes          # Needed so continues to the FAIL play
  - name: "FAIL >> Compliance check failed"
    fail:
      msg: "Non-compliant state encountered. Refer to the full report in {{ ans.dir_path }}/reports/{{ inventory_hostname }}_compliance_report.json"
    when: not nap_val.compliance_report.complies
  when: not ansible_check_mode          # Dont want to run validation in check_mode
  tags: [nap_val_fbc_bse, nap_val_tnt,nap_val_svc, nap_val, post_val, full]